spring.application.name=Payment-Service
server.port=8083
server.servlet.context-path=/payment
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
#spring.datasource.password=

stripe.api_key = ${stripe_api_key}
stripe.endpoint_secret =${stripe_endpoint_secret}
razorpay.key_id = ${razorpay_key_id}
razorpay.key_secret = ${razorpay_key_secret}

#register with eureka server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka